version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: anniversary_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: anniversary_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: